In [1]:
# creating a neuron

inputs = [1.2, 5.1, 2.1] # outputs from prev layer = inputs to the next layer of neurons
weights = [3.1, 2.1, 8.7]
bias = 3 # each neuron has a unique bias

# changing values here to the ones in second video

# 1 neuron has its own bias, and it takes in 3 inputs with 3 weights
inputs = [1, 2, 3] # input layer
weights = [0.2, 0.8, -0.5]
bias = 2

# computing neuron's output from its inputs, weights, and bias
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias 
print(output)

2.3


In [2]:
# now trying 4 inputs into 3 neurons

inputs = [1, 2, 3, 2.5] # input layer

# each neuron has separate weights for each input and its own unique bias
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

# computing values for this 3-neuron layer
output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1, 
        inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
        inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
print(output) # output from layer of 3 neurons

[4.8, 1.21, 2.385]


In [3]:
# zip function combines two lists element-wise (ex. zipping weights and biases generates a list of lists where the first list consists
# of the i-th weight and the i-th bias?)

weights = []
weights.append(weights1)
weights.append(weights2)
weights.append(weights3)

weights

[[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]

In [4]:
biases = [bias1, bias2, bias3]
biases

[2, 3, 0.5]

In [5]:
zip(weights, biases)

In [6]:
# condensed code for computing neuron layer's output
layer_outputs = []
for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

layer_outputs

[4.8, 1.21, 2.385]

In [7]:
# computing output but with numpy library
import numpy
output = numpy.dot(weights, inputs) + biases
print(output)

[4.8   1.21  2.385]


In [8]:
inputs = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

# need to transpose weights matrix so row1 = col2 dimension to allow matrix multiplication
output = numpy.dot(inputs, numpy.array(weights).T)
print(output)
output = output + biases
print(output)

[[ 2.8   -1.79   1.885]
 [ 6.9   -4.81  -0.3  ]
 [-0.59  -1.949 -0.474]]
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
