In [2]:
import sys
import numpy

In [3]:
X = [
    [1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # randomly initializing layer's weights (trying for range -0.1, +0.1)
        self.weights = 0.10 * numpy.random.randn(n_inputs, n_neurons) # returns array of shape (n_inputs, n_neurons) for the weights array
        self.biases = numpy.zeros((1, n_neurons)) # returns array of shape (1, n_neurons) filled with zeros for the biases array
    def forward(self, inputs):
        self.output = numpy.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = numpy.maximum(0, inputs)

In [7]:
def test1():
    layer1 = Layer_Dense(4, 5)
    layer1.forward(X)
    print(layer1.output)

    activation1 = Activation_ReLU()
    activation1.forward(layer1.output)
    print(activation1.output)

    layer2 = Layer_Dense(5, 2)
    layer2.forward(activation1.output)
    print(layer2.output)

    activation2 = Activation_ReLU()
    activation2.forward(layer2.output)
    print(activation2.output)

test1()

[[ 0.44717824 -0.7859664  -0.10983617  0.35750269  0.30768287]
 [ 0.31954115  0.15985204 -0.35544089  0.76572697  0.07326083]
 [ 0.02300985 -0.51765055  0.16446377  0.11163865 -0.51881834]]
[[0.44717824 0.         0.         0.35750269 0.30768287]
 [0.31954115 0.15985204 0.         0.76572697 0.07326083]
 [0.02300985 0.         0.16446377 0.11163865 0.        ]]
[[ 0.02991967 -0.02537532]
 [ 0.05005311 -0.0374718 ]
 [ 0.01931216 -0.00223106]]
[[0.02991967 0.        ]
 [0.05005311 0.        ]
 [0.01931216 0.        ]]
